/**
 * Generates Apache and nginx server configuration for deploying an LML project
 * as a single-page application.
 *
 * Architecture:
 *   - The compiled output directory contains .lml source files (not pre-built HTML).
 *   - A single index.html shell (generated by generateShellHtml) is served for
 *     every page route.
 *   - lml-runtime.js (generated by generateBrowserRuntime) runs in the browser,
 *     reads the URL, fetches the corresponding .lml file, parses it, and renders
 *     it into the #lml-app outlet.
 *   - .lml files are served as static text assets — the only "server rendering"
 *     is the initial shell; everything else is client-side.
 *
 * This means the server only needs two rules:
 *   1. Serve .lml files and other real assets (JS, CSS, images) as-is.
 *   2. Fall through everything else to index.html.
 */

// ---------------------------------------------------------------------------
// URL mapping utilities
// ---------------------------------------------------------------------------

/**
 * Converts a .lml file path (relative to the source root, using forward
 * slashes) to its canonical clean URL as seen in the browser.
 *
 * Examples:
 *   'index.lml'           → '/'
 *   'about.lml'           → '/about'
 *   'blog/index.lml'      → '/blog/'
 *   'blog/my-post.lml'    → '/blog/my-post'
 *   'docs/api/ref.lml'    → '/docs/api/ref'
 */
export function fileToUrl(relLml: string): string {
  const p = relLml.replace(/\\/g, '/');
  if (p === 'index.lml') return '/';
  if (p.endsWith('/index.lml')) {
    return '/' + p.slice(0, p.length - 'index.lml'.length);
  }
  return '/' + p.replace(/\.lml$/, '');
}

// ---------------------------------------------------------------------------
// Apache .htaccess
// ---------------------------------------------------------------------------

export interface ApacheOptions {
  /**
   * When true, serve /404.lml as the custom not-found page.
   * The runtime fetches it when the server returns 404 for a .lml file.
   * Requires a `404.lml` in your project root.
   * @default false
   */
  custom404?: boolean;
}

/**
 * Generates a `.htaccess` file for Apache 2.4+ that runs the LML SPA.
 *
 * Rules in order:
 *   1. Set MIME type for .lml files so fetch() receives clean text/plain.
 *   2. Pass .lml files through unchanged (served as static text assets).
 *   3. Pass real files (JS, CSS, images, etc.) through unchanged.
 *   4. Rewrite everything else to index.html (the SPA shell).
 *
 * Also sets security headers and cache-control:
 *   - index.html and .lml files: no-cache (content changes frequently)
 *   - JS/CSS/fonts/images:       1-year immutable (assume fingerprinted names)
 */
export function generateApacheHtaccess(options: ApacheOptions = {}): string {
  const custom404 = options.custom404 ?? false;

  const lines: string[] = [
    '# Generated by lmlc — do not edit by hand',
    '# Requires: mod_rewrite, mod_headers, mod_expires, mod_mime',
    '',
    'Options -Indexes',
    'DirectoryIndex index.html',
    '',
    '# Serve .lml files as plain text so the JS runtime can fetch them',
    '<IfModule mod_mime.c>',
    '  AddType "text/plain; charset=utf-8" .lml',
    '</IfModule>',
    '',
    '<IfModule mod_rewrite.c>',
    '  RewriteEngine On',
    '  RewriteBase /',
    '',
    '  # Pass .lml source files directly to the browser',
    '  RewriteRule \\.lml$ - [L]',
    '',
    '  # Pass existing static assets (JS, CSS, images, fonts, etc.)',
    '  RewriteCond %{REQUEST_FILENAME} -f',
    '  RewriteRule ^ - [L]',
    '',
    '  # Everything else → SPA shell',
    '  RewriteRule ^ index.html [L]',
    '',
    '</IfModule>',
    '',
    '# Security headers',
    '<IfModule mod_headers.c>',
    '  # Applied to all responses',
    '  Header always set X-Content-Type-Options "nosniff"',
    '  Header always set X-Frame-Options "SAMEORIGIN"',
    '  Header always set Referrer-Policy "strict-origin-when-cross-origin"',
    '  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"',
    '</IfModule>',
    '',
    '# Cache-control',
    '<IfModule mod_expires.c>',
    '  ExpiresActive On',
    '',
    '  # SPA shell — always revalidate so routing changes are picked up',
    '  <FilesMatch "^index\\.html$">',
    '    ExpiresDefault "access plus 0 seconds"',
    '    Header always set Cache-Control "no-cache, must-revalidate"',
    '  </FilesMatch>',
    '',
    '  # .lml page sources — short TTL so content edits propagate quickly',
    '  <FilesMatch "\\.lml$">',
    '    ExpiresDefault "access plus 0 seconds"',
    '    Header always set Cache-Control "no-cache, must-revalidate"',
    '  </FilesMatch>',
    '',
    '  # Fingerprinted static assets — immutable for 1 year',
    '  ExpiresByType text/css                   "access plus 1 year"',
    '  ExpiresByType application/javascript     "access plus 1 year"',
    '  ExpiresByType image/png                  "access plus 1 year"',
    '  ExpiresByType image/jpeg                 "access plus 1 year"',
    '  ExpiresByType image/webp                 "access plus 1 year"',
    '  ExpiresByType image/svg+xml              "access plus 1 year"',
    '  ExpiresByType image/x-icon               "access plus 1 year"',
    '  ExpiresByType font/woff2                 "access plus 1 year"',
    '  ExpiresByType font/woff                  "access plus 1 year"',
    '</IfModule>',
  ];

  if (custom404) {
    lines.push(
      '',
      '# Custom 404 — the lml-runtime fetches /404.lml automatically on a 404',
      '# response, so no special Apache rule is needed beyond having the file.',
      '# Uncomment below only if you also want Apache to serve a 404.html',
      '# for non-JS clients (bots, curl, etc.):',
      '# ErrorDocument 404 /404.html',
    );
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// nginx server block
// ---------------------------------------------------------------------------

export interface NginxOptions {
  /**
   * Value for the `server_name` directive.
   * @default 'example.com'
   */
  serverName?: string;
  /**
   * Absolute path to the output directory on the server.
   * @default '/var/www/html'
   */
  root?: string;
  /**
   * Port to listen on (HTTP). Ignored when `ssl` is true (443 is used).
   * @default 80
   */
  port?: number;
  /**
   * Add a server block that listens on 443 with placeholder SSL directives.
   * @default false
   */
  ssl?: boolean;
  /**
   * Add a second server block that redirects HTTP → HTTPS.
   * Only meaningful when `ssl` is also true.
   * @default false
   */
  httpsRedirect?: boolean;
  /**
   * When true, add an error_page 404 directive pointing at /404.html.
   * The lml-runtime fetches /404.lml in JS, but this covers non-JS clients.
   * @default false
   */
  custom404?: boolean;
}

/**
 * Generates an nginx server block for the LML SPA.
 *
 * Routing strategy:
 *   - .lml files: served directly as text/plain with no-cache headers.
 *   - Other static assets (JS, CSS, images): served with 1-year immutable cache.
 *   - Everything else: falls through to index.html (the SPA shell).
 *
 * Optional: HTTPS stanza, HTTP→HTTPS redirect, custom 404.
 */
export function generateNginxConf(options: NginxOptions = {}): string {
  const serverName    = options.serverName    ?? 'example.com';
  const root          = options.root          ?? '/var/www/html';
  const port          = options.port          ?? 80;
  const ssl           = options.ssl           ?? false;
  const httpsRedirect = options.httpsRedirect ?? false;
  const custom404     = options.custom404     ?? false;

  const blocks: string[] = [
    '# Generated by lmlc — do not edit by hand',
    '# Place in /etc/nginx/sites-available/<name> and symlink to sites-enabled/',
    '# Then run: nginx -t && systemctl reload nginx',
    '',
  ];

  // HTTP → HTTPS redirect block
  if (ssl && httpsRedirect) {
    blocks.push(
      'server {',
      '    listen 80;',
      '    listen [::]:80;',
      `    server_name ${serverName};`,
      '    return 301 https://$host$request_uri;',
      '}',
      '',
    );
  }

  const listenDirectives = ssl
    ? ['    listen 443 ssl http2;', '    listen [::]:443 ssl http2;']
    : [`    listen ${port};`, `    listen [::]:${port};`];

  const block: string[] = [
    'server {',
    ...listenDirectives,
    `    server_name ${serverName};`,
    `    root ${root};`,
    '    index index.html;',
    '    charset utf-8;',
    '',
  ];

  if (ssl) {
    block.push(
      '    # SSL — replace with your certificate paths',
      '    ssl_certificate     /etc/ssl/certs/' + serverName + '.crt;',
      '    ssl_certificate_key /etc/ssl/private/' + serverName + '.key;',
      '    ssl_protocols       TLSv1.2 TLSv1.3;',
      '    ssl_ciphers         HIGH:!aNULL:!MD5;',
      '    ssl_session_cache   shared:SSL:10m;',
      '',
    );
  }

  // Security headers
  block.push(
    '    # Security headers',
    '    add_header X-Content-Type-Options "nosniff" always;',
    '    add_header X-Frame-Options "SAMEORIGIN" always;',
    '    add_header Referrer-Policy "strict-origin-when-cross-origin" always;',
    '    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;',
    '',
  );

  // .lml files: serve as plain text, no caching
  block.push(
    '    # .lml source files — served as text, always revalidated',
    '    # The JS runtime fetches these on every navigation.',
    '    location ~* \\.lml$ {',
    '        default_type "text/plain; charset=utf-8";',
    '        add_header Cache-Control "no-cache, must-revalidate" always;',
    '        try_files $uri =404;',
    '    }',
    '',
  );

  // SPA shell
  block.push(
    '    # SPA shell — served for all HTML routes',
    '    # index.html is never cached so route changes are picked up immediately.',
    '    location / {',
    '        try_files $uri /index.html;',
    '        location = /index.html {',
    '            add_header Cache-Control "no-cache, must-revalidate" always;',
    '        }',
    '    }',
    '',
  );

  // Fingerprinted assets
  block.push(
    '    # Fingerprinted static assets — 1-year immutable cache',
    '    location ~* \\.(css|js|woff2|woff|ttf|png|jpg|jpeg|svg|webp|ico|gif)$ {',
    '        expires 1y;',
    '        add_header Cache-Control "public, immutable" always;',
    '    }',
    '',
  );

  if (custom404) {
    block.push(
      '    # Non-JS clients (bots, curl) get a plain 404 response.',
      '    # JS clients are handled by the lml-runtime fetching /404.lml.',
      '    error_page 404 /404.html;',
      '',
    );
  }

  // Deny dotfiles
  block.push(
    '    # Deny access to dotfiles (.htaccess, .git, etc.)',
    '    location ~ /\\. {',
    '        deny all;',
    '    }',
    '}',
  );

  blocks.push(block.join('\n'));
  return blocks.join('\n');
}
